from random import choice
from time import sleep
lista = [1, 2, 3, 4, 5]
choice = choice(lista)
print('Adivinhe em que número de 1 a 5 em que estou pensando: ')
guess = int(input('Digite um numero de 1 a 5: '))
if choice == guess:
    print('PRCESSANDO', end='')
    print('. ', end=' ')
    sleep(0.5)
    print('. ', end=' ')
    sleep(0.5)
    print('. ', end=' ')
    sleep(0.5)
    print('. ', end=' ')
    sleep(0.5)
    print('. ', end=' ')
    sleep(0.5)
    print('. ', end=' ')
    sleep(0.5)
    print('. ')
    print('Você acertou!!!')
else:
    print('PRCESSANDO', end=' ')
    print('. ', end=' ')
    sleep(0.5)
    print('. ', end=' ')
    sleep(0.5)
    print('. ', end=' ')
    sleep(0.5)
    print('. ', end=' ')
    sleep(0.5)
    print('. ', end=' ')
    sleep(0.5)
    print('. ', end=' ')
    sleep(0.5)
    print('. ')
    print('Você errou!!! pensei no número {}'.format(choice))

